entryPoints:
  web:
    address: ":80"

api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: /etc/traefik/dynamic-config
    watch: true

tracing:
  zipkin:
    httpEndpoint: http://zipkin:9411/api/v2/spans
    id128Bit: true
    sameSpan: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
